[token_map]
Client = 0
Distance = 1
UL-DL = 2

[legend]
label_order = [
"Client",
"UL-DL",
"Distance"
]

[filename_map]
delimiter = "_"

[optional]
# Change what units you want represented
# The default is Mbps (Megbit per second)
# Supported: Mbps, MBps, Gbps
# speed_unit = "Mbps"